apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "docker-cluster-one"
  namespace: "default"
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.128.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: quick-start
    version: v1.24.6
    controlPlane:
      replicas: 1
    variables:
      - name: imageRepository
        value: ""
      - name: etcdImageTag
        value: ""
      - name: coreDNSImageTag
        value: ""
      - name: podSecurityStandard
        value:
          enabled: true
          enforce: "baseline"
          audit: "restricted"
          warn: "restricted"
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: 1
        - class: default-worker # Adding a 2nd worker pool
          name: md-1
          replicas: 1
